# Generated by Django 3.2 on 2021-05-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.IntegerField(default=0)),
                ('currencyBase', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.IntegerField(default=0)),
                ('transationType', models.CharField(default='buy', max_length=10)),
                ('currency', models.CharField(default='INR', max_length=20)),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('money', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('rate', models.DecimalField(blank=True, decimal_places=7, max_digits=7, null=True)),
            ],
        ),
    ]
