# Generated by Django 3.2 on 2021-05-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wzxt_bgworker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economy',
            name='instance_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='instance_id',
        ),
        migrations.AddField(
            model_name='economy',
            name='instance_name',
            field=models.CharField(default='INS0', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='instance_name',
            field=models.CharField(default='INS0', max_length=20, unique=True),
        ),
    ]
