# Generated by Django 3.2 on 2021-05-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wzxt_bgworker', '0002_auto_20210502_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economy',
            name='instance_name',
            field=models.CharField(default='INS0', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='instance_name',
            field=models.CharField(default='INS0', max_length=20),
        ),
    ]
