# Generated by Django 3.2 on 2021-05-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wzxt_bgworker', '0003_auto_20210502_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=7),
        ),
    ]
