# Generated by Django 3.2 on 2021-05-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wzxt_bgworker', '0005_auto_20210504_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='money',
            new_name='volume',
        ),
    ]
