# Generated by Django 3.2 on 2021-05-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wzxt_bgworker', '0008_auto_20210504_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=7),
        ),
    ]
