# Generated by Django 3.2 on 2021-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wzxt_bgworker', '0009_auto_20210504_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='volume',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
    ]
