# Generated by Django 3.2 on 2021-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('money', models.IntegerField(default=0)),
                ('rate', models.DecimalField(blank=True, decimal_places=7, max_digits=7, null=True)),
            ],
        ),
    ]
