# Generated by Django 3.2 on 2021-05-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210501_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Economy',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
